// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIbL8mxfVcm2GDyflXzJv90hFLIS-j8wQ',
    appId: '1:408263536531:web:47b115ac5be5e0d8624266',
    messagingSenderId: '408263536531',
    projectId: 'kohere-98e63',
    authDomain: 'kohere-98e63.firebaseapp.com',
    storageBucket: 'kohere-98e63.firebasestorage.app',
    measurementId: 'G-954P4TB720',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNCBtMWoAHSPDX2aQCQ_IaCVVM4-bzOvo',
    appId: '1:408263536531:android:7f428b1608348583624266',
    messagingSenderId: '408263536531',
    projectId: 'kohere-98e63',
    storageBucket: 'kohere-98e63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSMAJiNj-_LWttD8XzlIDPEAToiJbBJhk',
    appId: '1:408263536531:ios:a6a59799e3b03595624266',
    messagingSenderId: '408263536531',
    projectId: 'kohere-98e63',
    storageBucket: 'kohere-98e63.firebasestorage.app',
    iosBundleId: 'com.example.kohere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSMAJiNj-_LWttD8XzlIDPEAToiJbBJhk',
    appId: '1:408263536531:ios:a6a59799e3b03595624266',
    messagingSenderId: '408263536531',
    projectId: 'kohere-98e63',
    storageBucket: 'kohere-98e63.firebasestorage.app',
    iosBundleId: 'com.example.kohere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIbL8mxfVcm2GDyflXzJv90hFLIS-j8wQ',
    appId: '1:408263536531:web:c43f0605b6d1bff8624266',
    messagingSenderId: '408263536531',
    projectId: 'kohere-98e63',
    authDomain: 'kohere-98e63.firebaseapp.com',
    storageBucket: 'kohere-98e63.firebasestorage.app',
    measurementId: 'G-S37TT6TMRS',
  );
}
